= Résumé
:Author:    Urbón Bayes, Pere
:Email:     <pere.urbon@gmail.com>
:Date:      05-10-2016
:Revision:  1.1
:doctitle:  Résumé
:icons: font
:source-highlighter: coderay
:noheader:
:notitle:

== Urbon-Bayes, Pere

[cols="2", frame="none", grid="none"]
|===
2+| icon:location-arrow[location-arrow] Wildenbruchstr 85 12045 Berlin, Germany.
| icon:phone[phone]  +49.157/81949910 | icon:envelope[envelope] pere.urbon@gmail.com
| icon:connectdevelop[connectdevelop] http://www.purbon.com |icon:github[github] http://github.com/purbon
|===

== I worked for

=== Freelance - _Software Architect, Search and Data Engineering Consultant_

[cols="2", frame="none", grid="none"]
|===
|Berlin, Germany| October 2016 - Present
2+| As a Software Architect on Search and Data Engineering I help my clients setup proper data engineering practices, this include help defining the data engineering architecture, the deployment on cloud,
on premises or hybrid, consulting on specific project needs, setting up educational workshops, setting best practices and software development.

Projects: 

* _Eurecat, Centre Tecnològic de Catalunya_: Helping the Big Data unit as Data Architect, coordinating the technical aspects for private projects. Also pushing
forward an internal big data cloud with proper integrations with Ansible, Open Stack, Elasticsearch and Hortonworks Data Platform.

* _The Walt Disney Company, Disney Research Zurich_: Revamp of an internal RDF Ontology Storage API PoC to make it production ready, this included a complete code refactoring, development of
test framework, introduction of best practices such as single responsibility, code deduplication, etc.

* _Eurecat, Centre Tecnològic de Catalunya_: As a Data Architect lead i participate in many internal and external projects where the definition of a data platform is a requirement, this projects goes
from assessments and improvements to the creation of new architectures to scale current needs or for new projects. I also participate in the planning and execution of EU, state and regional research projects in the big data space.

* _Springer Nature Gmbh_: As a Tech Lead and Search Chapter Lead I help the teams in the Berlin office build and deliver projects at scale focusing on great data engineering practices and enabling and coaching the organization 
on best practices to build highly personalized search experiences.
|===

=== Elasticsearch Gmbh - _Software Engineer_

[cols="2", frame="none", grid="none"]
|===
|Berlin, Germany| November 2014 - October 2016
2+| As a software engineer embedded in the logstash team I'm responsible of delivering new features, fixing issues, take care of the community, in the rich ecosystem of plugins, and the core engine. I'm part of the trainers team, being promoted to lead trainer after successful delivering several trainings.

I'm also able to help out in support, specially on issues escalation and customer calls.

During my journey I've been able to deliver talks at 7 conferences, and several user groups, also one invited talk at CERN.
|===

=== Fyber Gmbh - _Senior Software Engineer_

[cols="2", frame="none", grid="none"]
|===
|Berlin, Germany| June 2014 - November 2014
2+| As a software engineer in the backend data team we were responsible of the data integrity, aggregations and reports for the rest of the company. 
Dealing with things like Ruby, C, Kafka, Rails, Memcache, Redis and Exasol.
|===

=== Belectric IT Solutions Gmbh - _Software Architect_

[cols="2", frame="none", grid="none"]
|===
|Jena, Germany| March 2012 - June 2014
2+| As an architect and engineer lead I’m the responsible of handcrafting new apps for and by the energy management society. Helping clients and companies deal with
large amount of data, and helping our planet to be more green. With special focus on Smart Grid solutions, we provide solar energy companies with 
solutions to improve, and analyse, their production process. This projects include collaborations with top German Universities.
|===

=== Moviepilot Gmbh - _Senior Data Digester_

[frame="none", grid="none"]
|===
|Berlin, Germany| March 2011 - Feb 2012
2+| As a senior data digester I’m involved into every NoSQL use case detected inside the company. Specialized on Graph databases, developing algorithms and 
data modeling and analytics over some huge datasets.
|===

=== Data Management Group - _Senior Software Engineer_
[small]#Dept of Computer Architecture, Universitat Politècnica de Catalunya#

[frame="none", grid="none"]
|===
|Barcelona, Spain | May 2008 - Dec 2010
2+| As a DEX team member I’m the main developer taking on the evolution of the new visual management tool set. DEX is a new generation of database following
the graph database paradigm, specifically DEX has got very optimal performance times with database of TB. Also I’m in charge of the maintenance of Bibex, 
a bibliographic search application on top of DEX. The main technologies involved in my work are Java, J2EE and Python.
|===

=== Education

[source,json]
----
{
  "2009": "Master in Computer Science by Universitat Oberta de Catalunya",
}
----

=== Languages and education

[source,json]
----
"languages" : {
  "English": "Fluent",
  "Deutsche": "Conversation",
  "Catalan": "Native",
  "Spanish": "Native"
},
  "education" : {
    "2009": "Formal argumentation by Universitat Oberta de Catalunya",
    "2003": "E-Commerce Security. Universitat d’estiu de Sabadell",
    "2000": "Secondary school Technical speciality, IES Giola"
  }
----

== Topics of Interest

* Programming: Ruby, Java, Scala, Go, Git, Subversion.
* Databases/NoSQL: MySQL, Elasticsearch, Neo4j, MongoDB, Redis, PostgreSQL, SQL Server, Cassandra.
* Web stack: Sinatra, Ruby on Rails, HTML5, CoffeeScript, JQuery.
* Processing stack: Spark, Hadoop, Apache Nifi, Akka, Akka Streams, LogStash, Sidekiq, Resque.
* Analytics: Tableu, Pentaho, Grafana, Kibana.
* Geo Information systems: Leaflet.js, Geoserver, OpenGIS.
* Devops: Ansible, OpenStack, AWS, GoCD, Jenkins, Cloud Foundry, Docker.
* Projects: Scrum, Kanban, UML, Jira, Team building.
* OS: Linux (debian, ubuntu, redhat), Mac OS X.
* IDE: Vim, Eclipse, IntelliJ IDEA, Visual Studio.

== Talks, Conferences and Contributions

=== 2017

* Back to the future: Cap el futur de l'enginyeria de dades. Big data congress 2017. Barcelona, Spain. (https://bigdatacongress.barcelona/ponents/pere-urbon/[link])
* The Quantum Mechanics of Data Pipelines. Codemotion 2017. Berlin, Germany. (https://berlin2017.codemotionworld.com/speaker/3295/[link])
* Data Engineering without walls. Code talks 2017. Hamburg, Germany. (https://www.codetalks.de/de/2017/programm/data-engineering-without-walls[link])
* The Quantum Mechanics of Data Pipelines. Bed-Con 2017. Berlin, Germany. (http://bed-con.org/2017/talks/The-quantum-mechanics-of-data-pipelines[link])

=== 2016

* Parenting Processes. Froscon 2016, Sankt Augustin, Germany. (https://programm.froscon.de/2016/events/1727.html[link])
* Let's validate your releases with JRuby, RSpec & SSH. Ruby Meetup, Berlin, Germany. (http://www.rug-b.de/topics/let-s-validate-your-releases-with-jruby-rspec-and-ssh[link])
* What has been cooking at Elastic. Search Meetup, Berlin, Germany. (http://www.meetup.com/Search-UG-Berlin/events/230166132/[link])
* Ingesting Logs with style. OSDC 2016, Berlin Germany. (https://www.netways.de/en/events_trainings/osdc/archive/osdc2016/[link])

=== 2010-2015

* Hands on Elastic(Search). Librecon 2015, Santiago de Compostela, Spain. (http://www.librecon.io/conferencias/#taller-practico-sobre-elastic-search[link])
* Scaling Logstash, DevOps Meetup, Berlin, Germany. (http://www.meetup.com/blndevops/events/221953734/[link])
* Scaling Logstash: A Collection of War Stories. OSDC 2015, Berlin, Germany. (https://www.netways.de/?id=3020#c17318[link])
* Logstash, from theory to real life, Elasticsearch Meetup Berlin, Germany. (http://www.meetup.com/Search-UG-Berlin/events/219666153/[link])
* ELK, making sense of your data (not just for logs!), FOSDEM 2015, Brussels, Belgium. (https://archive.fosdem.org/2015/schedule/event/elk,_making_sense_of_your_data_not_just_for_logs!/[link])
* Making sense of your data with the ELK, Jan 2015 Elastic Meetup Barcelona, Spain. (http://www.meetup.com/Barcelona-Elastic-Fantastics/events/219060414/[link])
* The graph processing atelier, Eurucamp 2014, Berlin Germany. (https://speakerdeck.com/purbon/the-graph-processing-atelier[link])
* A simple hadoop scheduler. NoSQL Matters 2013, Cologne, Germany. (https://2014.nosql-matters.org/cgn/abstracts/#abstract_379886060[link])
* From Tables to Graph, The recsys use case. NoSQL Matters 2012, Cologne, Germany. (https://2012.nosql-matters.org/cgn/[link])
* NoSQL it doesnt hurt and its fun. Jornades de PLL 2011, Barcelona, Spain. (http://jpl.cpl.upc.edu/x-jornades/conferencies-convidades/bases-de-dades-nosql[link])
* Graph databases, The web of data storage. FOSDEM 2011, Brussels, Belgium
* Introduction to Graph Databases. Rug-B 2011, Berlin, Germany

==== Publications

* Logfile-Analyse: Even und Log Daten aufbereiten mit Logstash, Heise iX: Magazin für professionelle informationstechnik. I. Drost, P. Urbon-Bayes. (http://www.heise.de/ix/inhalt/2016/10/132/[link])
* Survey of Graph Database Performance on the HPC Scalable Graph Analysis Benchmark. IWGD 2010. D. Dominguez-Sal, P. Urbon-Bayes, et all. (http://dl.acm.org/citation.cfm?id=1927590[link])
* Mining Software Repositories. Computer Science Master Thesis. PUrbon. Jun 2009
* Ontology Driven Database. ForumCIS 2007. RLozano, XPastor, PUrbon and Elozano

==== Organization and Program Commitee

* FOSDEM Graph Processing Room. FOSDEM 2012-2014. Brussels, Belgium. (http://graphdevroom.org[link])
* NoSQL Matters Barcelona. 2012, 2013. Barcelona, Spain. (https://2012.nosql-matters.org/bcn/[link])
* Developer and organizer at Reunió Espanyola de Criptografia i Seguretat de la Inf. 2005-2006

== Other information

* Athlete and Duathlete with SCC-Berlin, 2012-2015. (Berlin, Germany), Athlete with CERRR, 2010-2011. (Igualada, Spain), Handbol Vilamajor, 1988-2000
