= Résumé
:Author:    Urbón Bayes, Pere
:Email:     <pere.urbon@gmail.com>
:Date:      05-10-2016
:Revision:  1.1
:doctitle:  Résumé
:icons: font
:source-highlighter: coderay
:noheader:
:notitle:

== Urbon-Bayes, Pere

[cols="2", frame="none", grid="none"]
|===
2+| icon:location-arrow[location-arrow] Wildenbruchstr 85 12045 Berlin, Germany.
| icon:phone[phone]  +49.157/81949910 | icon:envelope[envelope] pere.urbon@gmail.com
| icon:connectdevelop[connectdevelop] https://purbon.substack.com/ |icon:github[github] http://github.com/purbon
|===

== I worked for

include::work_for.adoc[]

<<<<

=== Education

[source,json]
----
{
  "2022": "MSc in Computational Engineering and Mathematics by Universitat Rovira i Virgili",
  "2009": "Computer Science Engineering by Universitat Oberta de Catalunya",
}
----

=== Languages

[source,json]
----
"languages" : {
  "English": "Fluent",
  "Deutsche": "Conversation",
  "Catalan": "Native",
  "Spanish": "Native"
}
----

== Topics of Interest

* Programming: Ruby, Java, Scala, Go, Python, Git, Subversion.
* Databases/NoSQL: MySQL, Kafka, ELK stack, Neo4j, MongoDB, Redis, PostgreSQL, SQL Server, Cassandra.
* Web stack: Micronaut.io, Spring Boot, PlayFramework, Ruby on Rails, HTML5, CoffeeScript, JQuery.
* Data and Analytics stack: Spark, Apache NiFi, Kafka Streams, Akka, Akka Streams. Tableu, Pentaho, Grafana, Kibana.
* Streaming Platforms: Confluent Platform / Apache Kafka.
* Devops: Ansible, OpenStack, Terraform, AWS, GCP, GoCD, Jenkins, Cloud Foundry, Kubernetes, Docker.
* Projects: Scrum, Kanban, SAFe, UML, Jira, Team building.

== Talks, Conferences and Contributions

During the years I have delivered many talks in Meetups and Conferences across Europe.
The slides can be found (https://speakerdeck.com/purbon[here]) and (https://github.com/purbon/slides-meetups-and-confs[here]).

=== Publications

* Logfile-Analyse: Even und Log Daten aufbereiten mit Logstash, Heise iX: Magazin für professionelle informationstechnik. I. Drost, P. Urbon-Bayes. (http://www.heise.de/ix/inhalt/2016/10/132/[link])
* Survey of Graph Database Performance on the HPC Scalable Graph Analysis Benchmark. IWGD 2010. D. Dominguez-Sal, P. Urbon-Bayes, et all. (http://dl.acm.org/citation.cfm?id=1927590[link])
* Ontology Driven Database. ForumCIS 2007. RLozano, XPastor, PUrbon and Elozano

=== Organization and Program Commitee

* FOSDEM Graph Processing Room. FOSDEM 2012-2014. Brussels, Belgium. (http://graphdevroom.org[link])
* NoSQL Matters Barcelona. 2012, 2013. Barcelona, Spain. (https://2012.nosql-matters.org/bcn/[link])

For an extended version of this resume, including a full list of talks, conferences and contributions please contact me.
