=== Senior Solutions Architect, Confluent Inc - Professional Services team

[cols="2", frame="none", grid="none"]
|===
<|Berlin, Germany 
>| October 2018 - Present
2+| As part of the Services department, has been engaged as Lead Consultant and Principal Engineer, architecting,
 deploying and scaling real-time data integration use cases using Confluent Platform/Kafka for top companies in EMEA.
|===

Achivements:

* Lead the integration work stream in a multi-year, multi-department project for a top tier telco in Germany. 
Delivered project objective on time, keep opertional excelence, while managing to scale up a team new to the technology. 
Enabled the company to reduce customer churn.
* Championed the develivery of self-service Kafka internally and externally, helping teams reduce the opertional cost and support team autonomy.
Created, developed and main mantainer for  https://github.com/kafka-ops/julie[JulieOps], a well adopted open source project for gitops.  

//Core activities, responsabilites and achievements:
//* Delivered critical architecture workshops, operational readiness, troubleshooting and migration exercices that enabled the project to be delivered on time following initial expectations. 
//* Developed Streaming applications using Kafka Streams, Flink and Kafka Connectfor Fraud detection, Customer360, Transaction unification and smaller ML use cases.
//* Championed the delivery of self-service solutions for the customers that allowed their teams to deliver faster archiving high levels of autonomy.
 
Topics:
[small]
[cols="3", frame="none", grid="none"]
|===
<a|
* Solution Architecture
* Engineering Leadership
<a|
* MLOps
* Fraud detection, Customer360
<a|
* Devops SME
* Change Data Capture SME
|===

=== Software Architect, Search and Data Engineering Consultant, Freelance

[cols="2", frame="none", grid="none"]
|===
<|Berlin, Germany
>|October 2016 - September 2018
2+| As a Software Architect on Search and Data Engineering I help my clients setup proper data engineering practices, this include help defining the data engineering architecture, the deployment on cloud,
on premises or hybrid, consulting on specific project needs, setting up educational workshops, setting best practices and software development.

Notable clients: _Outfittery Gmbh_, _Eurecat, Centre Tecnològic de Catalunya_, _Springer Nature Gmbh_, _The Walt Disney Company, Disney Research Zurich_, _Privalia SL_, _Geenapp SL_.
|===

Projects samples:

* Driving a team of engineers build a new generation data platform.
* Leading a cross functional team of software engineers, data engineers and scientist building data centric solutions.
* Build state of the art search solutions.
* Give educational workshops on topics such as Search and Data Engineering.


=== Software Engineer, Elasticsearch Gmbh

[cols="2", frame="none", grid="none"]
|===
<|Berlin, Germany
>|November 2014 - October 2016
2+| As a software engineer embedded in the logstash team I'm responsible of delivering new features, fixing issues, take care of the community, in the rich ecosystem of plugins, and the core engine. I'm part of the trainers team, being promoted to lead trainer after successful delivering several trainings.

I'm also able to help out in support, specially on issues escalation and customer calls.

During my journey I've been able to deliver talks at 7 conferences, and several user groups, also one invited talk at CERN.
|===

=== Senior Software Engineer,  Fyber Gmbh

[cols="2", frame="none", grid="none"]
|===
<|Berlin, Germany
>|June 2014 - November 2014
2+| As a software engineer in the backend data team we were responsible of the data integrity, aggregations and reports for the rest of the company.
Dealing with things like Ruby, C, Kafka, Rails, Memcache, Redis and Exasol.
|===